spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: developer
    password: password

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  description: "Dev version of bank service"
  version: "0.0.1"
  server:
    stage: "dev"
