server:
  error:
    include-message: always
    include-binding-errors: always

app:
  server:
    url: ${app.server.url}

spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/bankapp
    username: ${user.postgresql}
    password: ${password.postgresql}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

#logging:
#  level:
#    org.springframework: DEBUG



