app:
  server:
    url: ${app.server.url}

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: developer
    password: password

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none


  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml



